// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcIDXxgaTnGqLBcVZV8QCdCPOJpV6PvUY',
    appId: '1:781337657499:web:192b09be0eb7ffbbc8063e',
    messagingSenderId: '781337657499',
    projectId: 'timeboxer-f41c5',
    authDomain: 'timeboxer-f41c5.firebaseapp.com',
    storageBucket: 'timeboxer-f41c5.firebasestorage.app',
    measurementId: 'G-EV5CYDQ046',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcIDXxgaTnGqLBcVZV8QCdCPOJpV6PvUY',
    appId: '1:781337657499:web:0f021583a51bc920c8063e',
    messagingSenderId: '781337657499',
    projectId: 'timeboxer-f41c5',
    authDomain: 'timeboxer-f41c5.firebaseapp.com',
    storageBucket: 'timeboxer-f41c5.firebasestorage.app',
    measurementId: 'G-NBS4T6QF15',
  );

}