name: time_boxer_v01
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.2
  dotenv: ^4.2.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
    - .env
